import discord
import random

# List of roast responses based on trigger words
roast_responses = {
    "bro": ["You sound like you're 12.", "fym bro?? Im your master.?", "How dare you bro zone me."],
    "babe": ["hey there huzz.", "Wsp huzz", "Match my freak huzz."],
    "hi": ["hi? I ain't gonna talk to you gng.", "Who says that anymore?", "Hi"],
    "air": ["air? you lightweight i ain notice you.", "too heavy to think about you rn honey.", "AIIIIIIRRRR BALLLLLLLLL NIGGA!"],
    "dude": ["Dude? Is that still your thing?", "Dude, that's so 2010.", "Dude, you're not even cool."],
    "man": ["Man, are you trying to be funny?", "Man? Really?", "Man, you need some new material."],
    "what": ["What? Can't even finish a sentence?", "What? You lost your train of thought?", "What’s up with that?"],
    "why": ["Why? I don’t even know why you’re asking.", "Why? Please, stop.", "Why are you still talking?"],
    "lol": ["Lol? You think that’s funny?", "Lol? Was that supposed to be a joke?", "Lol? You're trying too hard."],
    "smh": ["SMH? You should be embarrassed.", "SMH? At least I’m not speechless like you.", "SMH? Good one, genius."],
    "okay": ["Okay? That's the best you can come up with?", "Okay? More like 'I'm out of ideas.'", "Okay? Try harder."],
    "really": ["Really? You’re still on about this?", "Really? You should reconsider your life choices.", "Really? That was your big idea?"],
    "seriously": ["Seriously? That’s what you’re going with?", "Seriously? How original.", "Seriously? You really said that?"],
    "shut up": ["Shut up? How about you try some original words?", "Shut up? More like just stop talking.", "Shut up? I’m tired of hearing it."],
    "shutup": ["Shut up? How about you try some original words?", "Shut up? More like just stop talking.", "Shut up? I’m tired of hearing it."],
    "lmao": ["Lmao? Yeah, right. Try again.", "Lmao? You’re laughing at your own joke?", "Lmao? Nice try, though."],
    "wow": ["Wow? That’s all you’ve got?", "Wow? You should be proud of yourself.", "Wow, I'm so impressed. Not."],
    "nah": ["Nah? I didn’t ask.", "Nah? Yeah, sure, whatever.", "Nah? Okay, keep telling yourself that."],
    "please": ["Please? Please, stop talking.", "Please? I beg you to be quiet.", "Please, do us both a favor and stop."],
    "help": ["Help? You’re the one who needs help.", "Help? You should try figuring it out yourself.", "Help? You really just asked for help with that?"],
    "yo": ["Yo? Is that your go-to?", "Yo? That’s so early 2000s.", "Yo? Are we back in high school?"],
    "chill": ["Chill? Nah, you need to do more than chill.", "Chill? Please, you're a walking disaster.", "Chill? More like learn to stop talking."],
    "bruh": ["Bruh? Really? That’s your response?", "Bruh? What are you, 16?", "Bruh? Try harder next time."],
    "yikes": ["Yikes? That’s all you got?", "Yikes? Oh, I'm shaking.", "Yikes? What a disaster."],
    "gtfo": ["GTFO? More like you should leave.", "GTFO? Who are you kidding?", "GTFO? You really said that?"],
    "srsly": ["Srsly? Is that how you talk?", "Srsly? That’s your response?", "Srsly? You should rethink your choices."],
    "for real": ["For real? You just said that?", "For real? Please, stop.", "For real? How original."],
    "nah fam": ["Nah fam? You’ve lost me.", "Nah fam? Keep telling yourself that.", "Nah fam? That was weak."],
    "facts": ["Facts? Are you serious?", "Facts? You sure about that?", "Facts? You should rethink your whole statement."],
    "damn": ["Damn? You really said that?", "Damn? That's the best you’ve got?", "Damn? Keep it together, man."],
    "idiot": ["Idiot? That’s rich coming from you.", "Idiot? Really?", "Idiot? You must be joking."],
    "bitch": ["Bitch? Are you serious?", "Bitch? Who taught you that?", "Bitch? Nice vocabulary, genius."],
    "asshole": ["Asshole? Nice words, pal.", "Asshole? Look who's talking.", "Asshole? Please, stop."],
    "fool": ["Fool? That’s a stretch.", "Fool? How original.", "Fool? You’ve got some nerve."],
    "stupid": ["Stupid? I think you need a dictionary.", "Stupid? No wonder you think that.", "Stupid? Look in the mirror."],
    "bastard": ["Bastard? Look who’s getting spicy.", "Bastard? Please, you’re embarrassing yourself.", "Bastard? That’s not even clever."],
    "dumb": ["Dumb? That’s rich coming from you.", "Dumb? Look who’s talking.", "Dumb? Nice try, Einstein."],
    "trash": ["Trash? You’re the one throwing it around.", "Trash? Really? That’s your best shot?", "Trash? How cute."],
    "fuck": ["Fuck? Is that really necessary?", "Fuck? Wow, how original.", "Fuck? You really need to work on your vocabulary."],
    "shit": ["Shit? You’re just mad now.", "Shit? That’s so 2007.", "Shit? You’ve got to be kidding."],
    "piss": ["Piss? Keep it together, bro.", "Piss? Take a chill pill.", "Piss? Don’t go overboard."],
    "douche": ["Douche? Is that your comeback?", "Douche? Keep your insults clean, alright?", "Douche? Very original."],
    "clown": ["Clown? Is that what you call yourself?", "Clown? You’ve got jokes.", "Clown? Stop clowning around."],
    "lame": ["Lame? You should be ashamed.", "Lame? What a clever response.", "Lame? Yeah, that’s a classic one."],
    "whore": ["Whore? You’re really reaching.", "Whore? What a disgraceful term. Suites you lol", "Whore? Look who’s mad."],
    "dick": ["Dick? Nice words, genius.", "You sound like a broken record.", "Please, stop. Its so small you ain't hitting this one, slut"],
    "wimp": ["Wimp? I didn’t know you cared.", "Wimp? That’s your insult?", "Cute comeback."],
    "loser": ["Loser? I guess you don’t know what that means.", "Look who’s salty.", "Keep talking."],
    "fomo": ["You’re missing out on life’s better choices.", "More like no life.", "You got FOMO but no personality."],
    "vibe": ["You couldn’t match a single mood.", "Your vibe’s stuck on ‘error.’", "You bring nothing to the party."],
    "lit": ["You think you’re lit but you’re just dim.", "That’s not lit, that’s just fire hazard.", "You’re not even close to lit."],
    "savage": ["You call it savage but it’s just petty.", "Only dramatic, not savage.", "You’re not savage, just annoying."],
    "ghost": ["You’re the one who gets ghosted, not the other way around.", "You ghost more than you talk.", "You couldn’t ghost a paper bag."],
    "flex": ["You’re flexing like it’s 2010.", "That’s not a flex, that’s just embarrassing.", "You act like you’re flexing, but it’s weak."],
    "finesse": ["You couldn’t finesse a paper bag.", "You finessed your way into disappointment.", "Your finesse game is weak."],
    "chill": ["You’re a whole meltdown.", "More like crash and burn.", "You scream anxiety, not chill."],
    "no cap": ["You’re straight capped.", "You’re all talk, no action.", "You can’t even cap properly."],
    "squad": ["More like awkward silence crew.", "Your squad’s as lit as a damp match.", "Are they still on break?"],
    "bae": ["You don’t even know what that means.", "You’re giving ‘wannabe influencer’ vibes.", "Bae? More like an outdated term."],
    "vibes": ["You’re a walking glitch.", "Your vibes have a bug in them.", "You say vibes but it’s straight up error 404."],
    "woke": ["You fell asleep, not woke.", "You say woke but can’t even stay awake.", "You’re just confusing."],
    "slaps": ["That slap was more of a light tap.", "You think that slaps but it barely taps.", "Your taste is weak."],
    "drip": ["That’s a drought, fam.", "You call that drip? More like a puddle.", "You missed the whole concept."],
    "simp": ["You’re the definition.", "No, that’s you living your best life.", "Simping for who? They’d block you first."],
    "glow up": ["You need a hard reset.", "Your glow’s on airplane mode.", "Glow up? You’re still buffering."],
    "vibe check": ["You failed that real quick.", "Sorry, you’re not eligible.", "You’re not passing the vibe check."],
    "litty": ["More like ‘taking a nap’ energy.", "That’s past your bedtime.", "Litty? That’s a stretch."],
    "yasss": ["You’re yelling for no reason.", "More like ‘no thanks’.", "You wish you had the energy."],
    "stan": ["You can’t even pronounce it correctly.", "You’re the definition of confusion.", "You’re not even close."],
    "big mood": ["You’re not big, just loud.", "More like no mood.", "That’s not a mood, that’s an error."],
    "w": ["Your L’s are so big they block the sun.", "You couldn’t win a game of rock-paper-scissors.", "Try again, champ."],
    "hype": ["Your hype’s on mute.", "It’s more like a whisper.", "You’re hyped but can’t back it up."],
    "drip": ["You missed the whole concept.", "More like a drought.", "You’re dripping in disappointment."],
    "goofy": ["You're like a TikTok filter no one asked for.", "That’s your default setting, huh?", "You're Disney-core but make it tragic."],
    "slay": ["More like delay.", "Maybe slay your ego.", "You haven’t even shown up."],
    "rizz": ["You got negative game.", "Your rizz expired in beta.", "You fumbled the bag before the convo started."],
    "ratio": ["You couldn’t ratio a calculator.", "Try again, champ.", "You say ratio but it’s not hitting."],
    "deadass": ["You’re deadass delusional.", "Tired of your energy.", "That’s from 2017, get with it."],
    "sus": ["You’re acting sus and crusty.", "Throwing sus like it’s 2020.", "You’re not slick, just weird."],
    "cringe": ["You’re giving ‘starter pack’ energy.", "You’re what cringe looks up to.", "You dress like a walking L."],
    "bet": ["You’ll flop again.", "You bet and still lose.", "You’re not even part of the game."],
    "noob": ["Bless you, still say noob?", "You peaked in Minecraft insults.", "You’re not new, just bad."],
    "bro": ["You peaked in middle school.", "You’re one ‘bro’ away from a personality.", "That’s your whole personality?"],
    "babe": ["I’m not your therapist.", "You need a mirror and a moment.", "Babe energy, but discount store version."],
    "hi": ["Dryest hi ever. Congrats.", "Say hi again, I dare you. With some spice.", "hi? That’s it?"],
    "air": ["You blend in with oxygen—unseen and unnecessary.", "You’re lighter than relevance.", "You’re like air, but musty."],
    "dude": ["Dude, your vibe’s buffering.", "You still say dude unironically? Be serious.", "You sound like a Vine reject."],
    "man": ["Man, you're exhausting.", "You're one inspirational quote away from snapping.", "You're giving ‘dad who peaked in high school’."],
    "what": ["Your brain loading again?", "You ask what like you didn’t just say nonsense.", "Try saying that with a clue next time."],
    "why": ["Because you make poor choices.", "The universe needed a joke.", "You ask why like you’re relevant."],
    "lol": ["No one’s laughing, not even you.", "Laughing? At your own flop?", "lol? You typed that with tears in your eyes."],
    "smh": ["Shake harder, maybe you’ll think straight.", "You really typed that like it hits.", "smh at your entire existence."],
    "okay": ["You say okay like that changed something.", "That was the driest okay of all time.", "Okay and irrelevant."],
    "really": ["Shocking, you can type?", "You sound like a clickbait thumbnail.", "You need a new script."],
    "seriously": ["You seriously thought that hit?", "That’s a wild amount of confidence.", "Seriously? You live like this?"],
    "shut up": ["You first.", "You talk like your mic’s stuck on mute anyway.", "Make me, iDroid."],
    "lmao": ["You typed lmao but your soul is crying.", "Even your laugh is mid.", "That joke aged like milk."],
    "wow": ["Wow indeed. You’re the low point of my day.", "You peaked at wow.", "You're a wow in lowercase energy."],
    "nah": ["Nah as in no friends?", "You deny like you're important.", "That was your final answer? Mid."],
    "please": ["Please get a new personality.", "You’re begging? I’m gagging.", "You beg like it’s a feature."],
    "help": ["Even ChatGPT can’t save you.", "You need divine intervention.", "You need more than help, sweetheart."],
    "yo": ["Yo? What is this, 2013?", "You’re not cool, you're cold.", "Yo and no substance."],
    "clown": ["You’re not funny, just loud.", "You don’t even need makeup to look clownish.", "You’re the whole circus, I’m just here for popcorn."],
    "lame": ["You typed that with flip-flops on.", "That was so dry I need water.", "You're the social version of buffering."],
    "dick": ["You bring nothing but flop energy.", "Your insult game is as short as your patience.", "You talk spicy but you’re mild AF."],
    "loser": ["Originality is not your strong suit, huh?", "You embody 'L'.", "You say loser, I hear projection."],
    "mid": ["You live, laugh, love mid.", "You’re below average trying to be average.", "Even mid doesn’t claim you."],
    "skull": ["Skull emoji doesn’t save your flop text.", "You died of cringe, not humor.", "You're laughing at your own L."],
    "based": ["You say based but act pressed.", "You're the opposite of based—confused.", "Based on what? Your last flop?"],
    "goofy": ["You're like a TikTok filter no one asked for.", "Goofy? That's your default setting.", "You're Disney-core but make it tragic."],
    "slay": ["Slay? More like delay.", "Slay... your ego maybe.", "Slay? You haven’t even shown up."],
    "rizz": ["You talking about rizz? You got negative game.", "Your rizz expired in beta.", "You fumbled the bag before the convo started."],
    "ratio": ["You say ratio like you're not already losing.", "You couldn’t ratio a calculator.", "Try again, champ."],
    "deadass": ["Deadass? You got that one from 2017.", "You’re deadass delusional.", "Deadass tired of your energy."],
    "sus": ["You’re not slick, just weird.", "You’re acting sus and crusty.", "You throw sus like it’s still 2020."],
    "cringe": ["You're giving ‘starter pack’ energy.", "You’re what cringe looks up to.", "You say cringe but dress like a walking L."],
    "bet": ["Bet? You’re not even part of the game.", "Bet that you’ll flop again.", "You bet and still lose."],
    "noob": ["You still say noob? Bless.", "You’re not new, just bad.", "You peaked in Minecraft insults."],
}

# Trigger words to look for in messages
trigger_words = list(roast_responses.keys())

# Excluded users list (If you want to exclude specific users)
excluded_users = [1212229549459374222, 1269821629614264362]  # Add user IDs to exclude

async def handle_diss(message):
    # Don't let the bot respond to its own messages or excluded users
    if message.author.bot or message.author.id in excluded_users:
        return

    # Check if the bot is mentioned
    if message.mentions and message.mentions[0] == message.guild.me:
        content = message.content.lower()
        
        # Check if the message contains any of the roast trigger words
        for word in trigger_words:
            if word in content:
                response = random.choice(roast_responses[word])
                await message.reply(f"{response}")
                break  # Stop checking once we find a match
